//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class bctc
    {
        public string mack { get; set; }
        public long TaiSanNganHan { get; set; }
        public long TienVaCacKhoanTuongDuongTien { get; set; }
        public long Tien { get; set; }
        public long CacKhoanTuongDuongTien { get; set; }
        public long CacKhoanDauTuTaiChinhNganHan { get; set; }
        public long ChungKhoanKinhDoanh { get; set; }
        public int Quy { get; set; }
        public int Nam { get; set; }
        public int ID { get; set; }
        public long DuPhongGiamGiaChungKhoanKinhDoanh { get; set; }
        public long DauTuNamGiuDenNgayDaoHan { get; set; }
        public long CacKhoanPhaiThuNganHan { get; set; }
        public long PhaiThuKhachHang { get; set; }
        public long TraTruocChoNguoiBan { get; set; }
        public long PhaiThuNoiBoNganHan { get; set; }
        public long PhaiThuTheoTienDoKeHoachHopDongXayDung { get; set; }
        public long PhaiThuVeChoVayNganHan { get; set; }
        public long CacKhoanPhaiThuKhac { get; set; }
        public long DuPhongPhaiThuNganHanKhoDoi { get; set; }
        public long TaiSanThieuChoXuLy { get; set; }
        public long ThueVaCacKhoanKhacPhaiThuNhaNuoc { get; set; }
        public long GiaoDichMuaBanLaiTraiPhieuChinhPhu { get; set; }
        public long TaiSanNganHanKhac { get; set; }
        public long HangTonKhoTotal { get; set; }
        public long HangTonKho { get; set; }
        public long DuPhongGiamGiaHangTonKho { get; set; }
        public long TaiSanNganHanKhacTotal { get; set; }
        public long ChiPhiTraTruocNganHan { get; set; }
        public long ThueGTGTDuocKhauTru { get; set; }
        public long TaiSanDaiHan { get; set; }
        public long CacKhoanPhaiThuDaiHan { get; set; }
        public long PhaiThuDaiHanCuaKhachHang { get; set; }
        public long TraTruocChoNguoiBanDaiHan { get; set; }
        public long PhaiThuVeChoVayDaiHan { get; set; }
        public long PhaiThuDaiHanKhac { get; set; }
        public long DuPhongPhaiThuKhoDoi { get; set; }
        public long TaiSanCoDinh { get; set; }
        public long TaiSanCoDinhHuuHinh { get; set; }
        public long NguyenGiaTSHH { get; set; }
        public long GiaTriHaoMonLuyKeTSHH { get; set; }
        public long TaiSanCoDinhThueTaiChinh { get; set; }
        public long NguyenGiaTSCDTTC { get; set; }
        public long GiaTriHaoMonLuyKeTSCDTTC { get; set; }
        public long TaiSanCoDinhVoHinh { get; set; }
        public long NguyenGiaTSCDVH { get; set; }
        public long GiaTriHaoMonLuyKeTSCDVH { get; set; }
        public long BatDongSanDauTu { get; set; }
        public long NguyenGiaBDSDT { get; set; }
        public long GiaTriHaoMonLuyKeBDSDT { get; set; }
        public long TaiSanDangDoDaiHan { get; set; }
        public long ChiPhiSxkdDoDangDaiHan { get; set; }
        public long ChiPhiXayDungCoBanDoDang { get; set; }
        public long DauTuTaiChinhDaiHan { get; set; }
        public long DauTuVaoCtyCon { get; set; }
        public long DauTuVaoCtyLienKetLienDoanh { get; set; }
        public long DauTuGopVonVaoDonViKhac { get; set; }
        public long DuPhongGiamGiaDauTuDaiHan { get; set; }
        public long C5_5_DauTuNamGiuDenNgayDaoHan { get; set; }
        public long TaiSanDaiHanKhac { get; set; }
        public long ChiPhiTraTruocDaiHan { get; set; }
        public Nullable<long> TaiSanThueThuNhapHoanLai { get; set; }
        public long ThietBiVatTuPhuTungThayTheDaiHan { get; set; }
        public long C6_4_TaiSanDaiHanKhac { get; set; }
        public long C6_5_KyQuyKyCuocDaiHan { get; set; }
        public long C6_6_LoiTheThuongMai { get; set; }
        public long TongTaiSan { get; set; }
        public long NoPhaiTra { get; set; }
        public long C1_NoNganHan { get; set; }
        public long C1_1_PhaiTraNguoiBanNganHan { get; set; }
        public long C1_2_NguoiMuaTraTienTruocNganHan { get; set; }
        public long C1_3_ThueVaCacKhoanPhaiNopNhaNuoc { get; set; }
        public long C1_4_PhaiTraNguoiLaoDong { get; set; }
        public long C1_5_ChiPhiPhaiTraNganHan { get; set; }
        public long C1_6_PhaiTraNoiBoNganHan { get; set; }
        public long C1_7_PhaiTraTheoTienDoKeHoachHDXD { get; set; }
        public Nullable<long> C1_8_DoanhThuChuaDuocThucHienNganHan { get; set; }
        public Nullable<long> C1_9_PhaiTraNganHanKhac { get; set; }
        public Nullable<long> C1_10_VayVaNoThueTaichinhNganHan { get; set; }
        public Nullable<long> C1_11_DuPhongPhaiTraNganHan { get; set; }
        public Nullable<long> C1_12_QuyKhenThuongPhucLoi { get; set; }
        public Nullable<long> C1_13_QuyBinhOnGia { get; set; }
        public Nullable<long> C1_14_GiaoDichMuaBanTraiPhieuChinhPhu { get; set; }
        public Nullable<long> C2_NoDaiHan { get; set; }
        public Nullable<long> C2_1_PhaiTraDaiHanNguoiBan { get; set; }
        public Nullable<long> C2_2_NguoiMuaTraTienTruocDaiHan { get; set; }
        public Nullable<long> C2_3_ChiPhiPhaiTraDaiHan { get; set; }
        public Nullable<long> C2_4_PhaiTraNoiBoVeVonKD { get; set; }
        public Nullable<long> C2_5_PhaiTraDaiHanNoiBoDaiHan { get; set; }
        public Nullable<long> C2_6_DoanhThuChuaThucHienDaiHan { get; set; }
        public Nullable<long> C2_7_PhaiTraDaiHanKhac { get; set; }
        public Nullable<long> C2_8_VayVaNoThueTaiChinhDaiHan { get; set; }
        public Nullable<long> C2_9_TraiPhieuChuyenDoi { get; set; }
        public Nullable<long> C2_11_ThueThuNhapHoanLaiPhaiTra { get; set; }
        public Nullable<long> C2_12_DuPhongPhaiTraDaiHan { get; set; }
        public Nullable<long> C2_13_QuyPhatTrienKhoaHocCongNghe { get; set; }
        public Nullable<long> II_VonChuSoHuu { get; set; }
        public Nullable<long> C1_VonChuSoHuu { get; set; }
        public Nullable<long> C1_1_VonGopCuaChuSoHuu { get; set; }
        public Nullable<long> C1_1_1_CoPhieuPhoThongCoQuyenBieuQuyet { get; set; }
        public Nullable<long> C1_1_2_CoPhieuUuDai { get; set; }
        public Nullable<long> C1_2_10_CoPhieuUuDai { get; set; }
        public Nullable<long> C1_2_ThangDuVonCoPhan { get; set; }
        public Nullable<long> C1_3_QuyenChonChuyenDoiTraiPhieu { get; set; }
        public Nullable<long> C1_4_VonKhacCuaChuSoHuu { get; set; }
        public Nullable<long> C1_5_CoPhieuQuy { get; set; }
        public Nullable<long> C1_6_ChenhLechDanhGiaLaiTaiSan { get; set; }
        public Nullable<long> C1_7_ChenhLechTyGiaHoiDoai { get; set; }
        public Nullable<long> C1_8_QuyDauTuPhatTrien { get; set; }
        public Nullable<long> C1_9_QuyHoTroSapXepDoanhNghiep { get; set; }
        public Nullable<long> C1_10_QuyKhacThuocVonChuSoHuu { get; set; }
        public Nullable<long> C1_11_LoiNhuanSauThueChuaPhanPhoi { get; set; }
        public Nullable<long> C1_11_1_LNSTChuaPhanPhoiLuyKeDenCuoiKyTruoc { get; set; }
        public Nullable<long> C1_11_2_LNSTChuaPhanPhoiKyNay { get; set; }
        public Nullable<long> C1_12_NguonVonDauTuXDCB { get; set; }
        public Nullable<long> C1_13_LoiIchCoDongKhongKiemSoat { get; set; }
        public Nullable<long> C1_14_PhuTroiHopNhatCongTyCon { get; set; }
        public Nullable<long> C2_NguonKinhPhiVaCacQuyKhac { get; set; }
        public Nullable<long> C2_1_NguonKinhPhi { get; set; }
        public Nullable<long> C2_2_NguonKinhPhiDaHinhThanhTSCD { get; set; }
        public Nullable<long> III_LoiIchCuaCoDongThieuSo { get; set; }
        public Nullable<long> C1_DoanhThuBanHangVaCungcapDV { get; set; }
        public Nullable<long> C2_CacKhoanGiamTruDanhThu { get; set; }
        public Nullable<long> C3_DoanhThuThuanVeBanHangVaCungCapDV { get; set; }
        public Nullable<long> C4_GiaVonHangBan { get; set; }
        public Nullable<long> C5_LoiNhuanGopVeBanHangVaCungCapDV { get; set; }
        public Nullable<long> C6_DoanhThuHoatDongTaiChinh { get; set; }
        public Nullable<long> C7_ChiPhiTaiChinh { get; set; }
        public Nullable<long> C7_1_ChiPhiLaiVay { get; set; }
        public Nullable<long> C8_PhanLaiLoTrongCtyLienDoanhLienKet { get; set; }
        public Nullable<long> C9_ChiPhiBanHang { get; set; }
        public Nullable<long> C10_ChiPhiQuanLyDoanhNghiep { get; set; }
        public Nullable<long> C11_LoiNhuanThuanTuHoatDongKinhDoanh { get; set; }
        public Nullable<long> C12_ThuNhapKhac { get; set; }
        public Nullable<long> C13_ChiPhiKhac { get; set; }
        public Nullable<long> C14_LoiNhuanKhac { get; set; }
        public Nullable<long> C15_TongLoiNhuanKeToanTruocThue { get; set; }
        public Nullable<long> C16_ChiPhiThueTNDNHienHanh { get; set; }
        public Nullable<long> C17_ChiPhiThueTNDNHoanLai { get; set; }
        public Nullable<long> C18_LoiNhuanSauThueTNDN { get; set; }
        public Nullable<long> C18_1_LoiIchCuaCoDongThieuSo { get; set; }
        public Nullable<long> C18_2_LoiNhuanSauThueCuaCtyMe { get; set; }
        public Nullable<long> C19_LaiCoBanTrenCoPhieu { get; set; }
        public bool IsChecked { get; set; }
    }
}
